# Generated by Django 3.0.8 on 2020-07-10 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('problem_statement', models.TextField()),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.FileField(upload_to='')),
                ('output', models.FileField(upload_to='')),
                ('task_num', models.PositiveSmallIntegerField()),
                ('sub_task_num', models.PositiveSmallIntegerField()),
                ('error_message', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemModel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='problemtestmodel',
            constraint=models.UniqueConstraint(fields=('task_num', 'sub_task_num'), name='unique task number'),
        ),
    ]
